In [3]:
#Libraries
import numpy as np
import pandas as pd

In [24]:
class MyPerceptronBCE:

    def __init__(self, learning_rate=0.1, n_iterations=1000):

        self.lr=learning_rate
        self.epochs =n_iterations
        self.weights = None
        self.bias = None

    def fit(self, X, y):

        self.weights = np.zeros(X.shape[1])
        self.bias = 0

        for epoch in range(self.epochs):

            for i in range(X.shape[0]):

                y_pred = (self.sigmoid(np.dot(self.weights,X[i]) + self.bias)>0).astype(int)

                self.weights = self.weights + self.lr * (y[i] - y_pred)*X[i]
                self.bias = self.bias + self.lr * (y[i] - y_pred)

        print("Training complete")

        print(self.weights)
        print(self.bias)
        
    def sigmoid(self,x):
        return 1/(1+np.power(np.e,-x))


    def predict(self,X):

        y_pred=[]

        for i in range(X.shape[0]):

            y_pred.append(self.sigmoid(np.dot(self.weights,X[i]) + self.bias)>0)

        return np.array(y_pred).astype(int)

In [4]:
(np.array([1,2,3,4])>1).astype(int)

array([0, 1, 1, 1])

In [6]:
def sigmoid(x):
    return 1/(1+np.power(np.e,-x))

In [7]:
sigmoid(np.array([1,2]))

array([0.73105858, 0.88079708])

In [8]:
import pandas as pd

In [9]:
data=pd.read_csv('student.csv')

In [10]:
data.head()

marks1    marks2  result
0  3.405069  1.167249       1
1  1.373927 -0.738440       1
2  1.220778 -0.197186       1
3  1.439881  0.052957       1
4 -0.756672 -0.127077       0

In [11]:
X=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

In [12]:
type(X)

numpy.ndarray

In [13]:
y.shape

(100,)

In [14]:
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [15]:
X_train,X_test,y_train,y_test =train_test_split(X,y,test_size=0.2)

In [25]:
model=MyPerceptronBCE()
model.fit(X_train,y_train)

C:\Users\SAMPS\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:30: RuntimeWarning: overflow encountered in power


Training complete
[450.61273005 -48.79579488]
-533.3000000000527


In [26]:
y_pred=model.predict(X_test)

C:\Users\SAMPS\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:30: RuntimeWarning: overflow encountered in power


In [27]:
accuracy_score(y_test,y_pred)

1.0

In [28]:
y_pred

array([0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1])

In [22]:
sum(y_test)

14